#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    reason = "build scripts are expected to panic on configuration errors"
)]

use std::path::{Path, PathBuf};

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as BASE64;
use sha2::{Digest, Sha256};
use vergen_gitcl::{Emitter, GitclBuilder};

fn main() {
    let git = GitclBuilder::default().sha(true).build().unwrap();

    Emitter::new()
        .add_instructions(&git)
        .unwrap()
        .emit()
        .unwrap();

    emit_inline_hashes().expect("inline-asset hash discovery failed");
    emit_importmap_hash().expect("importmap hash computation failed");
}

/// The importmap inlined on every page maps the `@homework` bare specifier
/// to `/homework.js?v=<git-sha>`. Its body is synthesised at build time
/// (not read from a file), so we compute its hash here too — same
/// SHA-256-then-base64 mechanics as [`emit_inline_hashes`], but the bytes
/// come from formatting against the short git SHA vergen-gitcl uses for
/// `ASSET_VERSION`. The constants we emit are referenced by `csp.rs` to
/// build the `InlineImportmap` paired with its CSP source.
///
/// Format must stay byte-identical to `layout::page`'s rendered importmap.
fn emit_importmap_hash() -> std::io::Result<()> {
    // Match `GitclBuilder::default().sha(true)` (short SHA via `git
    // rev-parse --short HEAD`). If vergen ever changes its abbreviation
    // strategy this would drift — the new e2e tests catch that as a CSP
    // violation in the browser.
    let sha = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()?;
    let sha = std::str::from_utf8(&sha.stdout)
        .expect("git short sha is ASCII")
        .trim();

    let body = format!(r#"{{"imports":{{"@homework":"/homework.js?v={sha}"}}}}"#);
    let hash_b64 = BASE64.encode(Sha256::digest(body.as_bytes()));

    let out = format!(
        "// Auto-generated by build.rs. Do not edit by hand.\n\
         pub const IMPORTMAP_BODY: &str = {body:?};\n\
         pub const IMPORTMAP_HASH_B64: &str = {hash_b64:?};\n"
    );
    let out_dir = std::env::var_os("OUT_DIR").expect("OUT_DIR is always set by cargo");
    std::fs::write(Path::new(&out_dir).join("importmap.rs"), out)?;

    // Re-run when HEAD moves (covers regular commits) or when refs change
    // (covers checkouts of detached HEADs in CI).
    println!("cargo:rerun-if-changed=.git/HEAD");
    println!("cargo:rerun-if-changed=.git/refs/heads");
    Ok(())
}

/// Walk `src/service/` and emit one `pub const` per `.js` / `.css` file
/// holding its base64-encoded SHA-256 digest.
///
/// The generated file lives in `$OUT_DIR/inline_hashes.rs`. `csp.rs`
/// `include!`s it. Constants are referenced by name from `inline_script!`
/// / `inline_style!` declarations elsewhere in the tree, so unused
/// entries are dead code (harmless) and any typo at the reference site
/// is a hard compile error — keeping the inline-asset registry
/// "self-healing" without a manifest.
///
/// Name mangling: strip `src/service/`, replace `/`/`-`/`.` etc. with
/// `_`, uppercase, append `_HASH_B64`. Example:
/// `src/service/exercises/clock.css` → `EXERCISES_CLOCK_CSS_HASH_B64`.
///
/// CRLF normalisation: bytes are stripped of `\r` before hashing, so a
/// Windows clone whose working tree holds CRLF endings still produces
/// the same digest the HTML5 parser computes from the served content
/// (which is always LF inside `<script>` / `<style>`).
fn emit_inline_hashes() -> std::io::Result<()> {
    let root = Path::new("src").join("service");
    let mut files = Vec::new();
    walk(&root, &mut files)?;
    files.sort();

    let mut out = String::from("// Auto-generated by build.rs. Do not edit by hand.\n\n");
    for path in &files {
        let bytes = std::fs::read(path)?;
        let normalised: Vec<u8> = bytes.into_iter().filter(|b| *b != b'\r').collect();
        let hash_b64 = BASE64.encode(Sha256::digest(&normalised));
        let const_name = const_name_for(path.strip_prefix(&root).unwrap());

        out.push_str(&format!("pub const {const_name}: &str = \"{hash_b64}\";\n"));
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let out_dir = std::env::var_os("OUT_DIR").expect("OUT_DIR is always set by cargo");
    let dest = Path::new(&out_dir).join("inline_hashes.rs");
    std::fs::write(dest, out)?;
    Ok(())
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) -> std::io::Result<()> {
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            walk(&path, out)?;
        } else if matches!(
            path.extension().and_then(|s| s.to_str()),
            // `.json` covers speculation-rules bodies, `.jsonld` covers
            // JSON-LD blocks — both get inlined into pages and need a
            // CSP hash apiece.
            Some("js" | "css" | "json" | "jsonld")
        ) {
            out.push(path);
        }
    }
    Ok(())
}

fn const_name_for(rel: &Path) -> String {
    let mut name = String::new();
    for component in rel.components() {
        if let std::path::Component::Normal(part) = component {
            if !name.is_empty() {
                name.push('_');
            }
            for ch in part.to_string_lossy().chars() {
                if ch.is_ascii_alphanumeric() {
                    name.push(ch.to_ascii_uppercase());
                } else {
                    // `/`, `-`, `.`, `_` and any other punctuation all
                    // collapse to a single underscore in the const name.
                    name.push('_');
                }
            }
        }
    }
    name.push_str("_HASH_B64");
    name
}
