app = 'homework'
primary_region = 'fra'

[experimental]
auto_rollback = true

[processes]
app = "--http 0.0.0.0:8080 --https 0.0.0.0:8443"

[env]
RUST_LOG = 'info,homework=debug,rama_http=debug,rama_http_core=info'

[[services]]
protocol = "tcp"
internal_port = 8080
processes = ['app']

    [services.concurrency]
    type = "connections"
    soft_limit = 1000
    hard_limit = 2000

    [[services.ports]]
    port = 80
    handlers = ["proxy_proto"]

    [[services.tcp_checks]]
    interval = "15s"
    timeout  = "5s"
    grace_period = "1s"
    restart_limit = 0

[[services]]
protocol = "tcp"
internal_port = 8443
processes = ['app']

    [services.concurrency]
    type = "connections"
    soft_limit = 1000
    hard_limit = 2000

    [[services.ports]]
    port = 443
    handlers = ["proxy_proto"]

    [[services.tcp_checks]]
    interval = "15s"
    timeout  = "5s"
    grace_period = "1500s"
    restart_limit = 0

[[vm]]
  size = 'shared-cpu-1x'
