app = 'homework'
primary_region = 'fra'

[experimental]
auto_rollback = true

[env]
  RUST_LOG = "info,homework=debug,rama_http=debug,rama_http_core=info"

[[services]]
protocol = "tcp"
internal_port = 8080

    [services.concurrency]
    type = "connections"
    soft_limit = 1000
    hard_limit = 2000

    [[services.ports]]
    port = 80

    [[services.tcp_checks]]
    interval = "15s"
    timeout  = "2s"
    grace_period = "5s"
    restart_limit = 0
